spring:
  profiles:
    active:
      - dev
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

fitclub:
  app:
    jwtExpiration: 86400
    jwtSecret: jwtFitClubSecretKey
#---
#spring:
#  config:
#    activate:
#      on-profile: prod
#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.MySQL57Dialect
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/newprojdb
#    username: root
#    password: root
#fitclub:
#  upload-path: uploads-prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/newprojdb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
fitclub:
  upload-path: uploads-dev

---
spring:
  config:
    activate:
      on-profile: test
fitclub:
  upload-path: uploads-test