spring:
  profiles:
    active:
      - dev
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100

  mail:
    host: smtp.gmail.com
    username: fitclub.by.alexnec@gmail.com
    password: kwwierdeowlqmjjf
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

jwt:
  secret: FitClubJWTSecretKey
  expirationInMs: 60480000

---
spring:
  config:
    activate:
      on-profile: prod
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL57Dialect

  datasource:
    url: jdbc:mysql://localhost:3306/newprojdb
    username: root
    password: root
fitclub:
  upload-path: uploads-prod

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/testing9post
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
fitclub:
  upload-path: uploads-dev

---
spring:
  config:
    activate:
      on-profile: test
fitclub:
  upload-path: uploads-test